name: solemate
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.12
  - numpy==1.24.3
  - scikit-learn==1.2.1
  - scikit-image==0.19.2
  - pandas==1.5.3
  - matplotlib==3.7.1
  - pillow==9.4.0
  - scipy==1.10.1
  - jupyter
  - plotly==5.6.0
  - seaborn
  - streamlit==1.24.1
